
from fastapi import FastAPI
from pydantic import BaseModel
import google.generativeai as genai
import os
from fastapi.middleware.cors import CORSMiddleware

# ✅ Load Environment Variables
GEMINI_KEY = os.getenv("GEMINI_API_KEY")
genai.configure(api_key=GEMINI_KEY)

# ✅ Create FastAPI app
app = FastAPI()

# ✅ Enable CORS (Allow frontend to call backend)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # You can replace "*" with your Firebase domain
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ✅ Request Model
class ChatRequest(BaseModel):
    message: str

# ✅ Chat Endpoint
@app.post("/chat")
async def chat_endpoint(request: ChatRequest):
    user_message = request.message.strip()
    print(f"Received: {user_message}")

    if not GEMINI_KEY:
        return {"reply": "⚠️ Gemini API key not found. Using fallback bot reply."}

    try:
        # ✅ Use Gemini Model
        model = genai.GenerativeModel("gemini-1.5-flash")
        response = model.generate_content(user_message)

        # ✅ Extract reply safely
        bot_reply = (
            response.candidates[0].content.parts[0].text
            if response and response.candidates
            else "⚠️ No reply generated by Gemini."
        )

    except Exception as e:
        bot_reply = f"❌ Gemini API Error: {str(e)}"

    print("DEBUG REPLY:", bot_reply)
    return {"reply": bot_reply}

# ✅ Root Endpoint
@app.get("/")
async def root():
    return {"message": "FastAPI Chatbot with Gemini 1.5 API 🚀"}
